### ISSUE TITLE
Music doesnt work?

### ISSUE THREAD

**Issue by Gershy13** [alexa-pi/AlexaPi#310]
Does any music work at all? Ive linked my spotify in the alexa app, but it wont play spotify or amazon music or anything? 
Help please?

Thanks
Gershy13

**Comment by maso27** [comment]
You can play stations from iHeartRadio

On Sep 2, 2017 10:26 AM, "Gershy13" <notifications@github.com> wrote:

Does any music work at all? Ive linked my spotify in the alexa app, but it
wont play spotify or amazon music or anything?
Help please?

Thanks
Gershy13

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexa-pi/AlexaPi/issues/310>, or mute the thread

**Comment by Gershy13** [comment]
so no normal music services work? spotify, google play, youtube, etc.

**Comment by maso27** [comment]
No.
If you use an Apple device, you can stream to it with Airplay.

**Comment by renekliment** [comment]
https://github.com/alexa-pi/AlexaPi/wiki/Q&A-(FAQ)#does-alexapi-support-amazon-music
